version: '3'
services:
  app:
    build: ./api-service
    ports:
     - "8082:3000"
    depends_on:
     - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: admin
      DATABASE_PW: yes123
      DATABASE_DB: SPOTIFY
      DATABASE_PORT: 5432
  postgres:
    container_name: postgres
    build: ./database-service
    ports:
      - "2345:5432"